[project]
name = "smarthammer"
dynamic = ["version"]
requires-python = ">= 3.10"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["hammer*"]