name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install elan (Lean version manager) and Lean 4
    - name: Install elan and Lean 4
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
        
    # Clone REPL first to get the Lean version
    - name: Clone REPL
      run: |
        git clone https://github.com/leanprover-community/repl.git
        
    # Install specific Lean version from REPL's toolchain
    - name: Install specific Lean version
      run: |
        cd repl
        LEAN_VERSION=$(cat lean-toolchain)
        elan default $LEAN_VERSION

    # Build REPL
    - name: Build REPL
      run: |
        cd repl
        lake update
        lake build
        echo "REPL_PATH=${{ github.workspace }}/repl/test/Mathlib" >> $GITHUB_ENV
        cd test/Mathlib
        lake exe cache get > /dev/null

    # Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pexpect python-dotenv

    # Create .env file with REPL path
    - name: Setup environment
      run: |
        echo "REPLPATH=${{ env.REPL_PATH }}" > .env

    # Run tests
    - name: Run tests
      run: |
        PYTHONPATH=${{ github.workspace }}/src pytest test/